// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSMS.Models;

namespace OSMS.Migrations
{
    [DbContext(typeof(OSMSContext))]
    [Migration("20200616235203_UpdateRowVersionColumnForStudent")]
    partial class UpdateRowVersionColumnForStudent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OSMS.Models.Instructor", b =>
                {
                    b.Property<string>("InstructorID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("timestamp");

                    b.Property<int>("StandardID")
                        .HasColumnType("int");

                    b.HasKey("InstructorID");

                    b.HasIndex("RoleID");

                    b.HasIndex("StandardID");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("OSMS.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("OSMS.Models.Standard", b =>
                {
                    b.Property<int>("StandardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StandardName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("StandardID");

                    b.ToTable("Standards");
                });

            modelBuilder.Entity("OSMS.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("timestamp");

                    b.Property<int>("StandardID")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudentID");

                    b.HasIndex("RoleID");

                    b.HasIndex("StandardID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("OSMS.Models.Instructor", b =>
                {
                    b.HasOne("OSMS.Models.Role", "Role")
                        .WithMany("Instructors")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSMS.Models.Standard", "Standard")
                        .WithMany("Instructors")
                        .HasForeignKey("StandardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OSMS.Models.Student", b =>
                {
                    b.HasOne("OSMS.Models.Role", "Role")
                        .WithMany("Students")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSMS.Models.Standard", "Standard")
                        .WithMany("Students")
                        .HasForeignKey("StandardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
